--------------------creaciones de la fact table y sus dimensiones

--creacion de la fact table ventas
CREATE TABLE FACT_Ventas (
    ID_Venta NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Producto NUMBER NOT NULL,
    ID_Sucursal NUMBER NOT NULL,
    ID_Cliente NUMBER NOT NULL,
    ID_Tiempo NUMBER NOT NULL,
    Cantidad_Vendida NUMBER NOT NULL,
    Total_Venta NUMBER(18, 2) NOT NULL
);

--tabla dimension para id producto
CREATE TABLE DIM_Producto (
    ID_Producto NUMBER PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL,
    Descripcion VARCHAR2(200),
    Precio NUMBER(18, 2) NOT NULL,
    ID_Categoria NUMBER,
    FOREIGN KEY (ID_Categoria) REFERENCES Categoria(ID_Categoria)
);

--tabla dimension para id_sucursal
CREATE TABLE DIM_Sucursal (
    ID_Sucursal NUMBER PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL,
    ID_Direccion NUMBER,
    FOREIGN KEY (ID_Direccion) REFERENCES Direccion(ID_Direccion)
);


--tabla dimension para id_cliente
CREATE TABLE DIM_Cliente (
    ID_Cliente NUMBER PRIMARY KEY,
    Nombre VARCHAR2(100) NOT NULL,
    Apellido_1 VARCHAR2(100) NOT NULL,
    Apellido_2 VARCHAR2(100),
    Telefono NUMBER NOT NULL,
    Correo VARCHAR2(200),
    ID_Direccion NUMBER,
    FOREIGN KEY (ID_Direccion) REFERENCES Direccion(ID_Direccion)
);


--tabla dimension para id_tiempo
CREATE TABLE Dim_Tiempo (
    ID_Tiempo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Fecha DATE NOT NULL,
    Año NUMBER NOT NULL,
    Mes NUMBER NOT NULL,
    Dia NUMBER NOT NULL
);


------------------------inserts para las tablas dimensiones---------------------------

--inserts en DIM_Producto
INSERT INTO DIM_Producto (ID_Producto, Nombre, Descripcion, Precio, ID_Categoria)
SELECT ID_Producto, Nombre, Descripcion, Precio, ID_Categoria FROM Producto;

--inserts en DIM_sucursal
INSERT INTO DIM_Sucursal (ID_Sucursal, Nombre, ID_Direccion)
SELECT ID_Sucursal, Nombre, ID_Direccion FROM Sucursal;

--inserts en DIM_Cliente
INSERT INTO Dim_Cliente (ID_Cliente, Nombre, Apellido_1, Apellido_2, Telefono, Correo, ID_Direccion)
SELECT ID_Cliente, Nombre, Apellido_1, Apellido_2, Telefono, Correo, ID_Direccion FROM Cliente;

--inserts en DIM_tiempo (usando extract para los numeros en especifico de dia, mes y anio
INSERT INTO Dim_Tiempo (Fecha, Año, Mes, Dia)
SELECT DISTINCT Fecha,
       EXTRACT(YEAR FROM Fecha) AS Año,
       EXTRACT(MONTH FROM Fecha) AS Mes,
       EXTRACT(DAY FROM Fecha) AS Dia
FROM Venta;


--inserts en la fact table FACT_Ventas
INSERT INTO Fact_Ventas (ID_Producto, ID_Sucursal, ID_Cliente, ID_Tiempo, Cantidad_Vendida, Total_Venta)
SELECT 
    v.ID_Producto, 
    v.ID_Sucursal, 
    v.ID_Cliente, 
    (SELECT ID_Tiempo FROM Dim_Tiempo WHERE Fecha = v.Fecha) AS ID_Tiempo,
    v.Cantidad_Vendida, 
    v.Total_Venta
FROM Venta v;

commit;




